### ISSUE TITLE
SQL Operations setup is not going through

### ISSUE THREAD

**Issue by eliassal** [Microsoft/sqlopsstudio#1035]
- SQL Operations Studio Version:  0.27.3
On the url
https://docs.microsoft.com/en-us/sql/sql-operations-studio/download#get-sql-operations-studio-preview-for-linux
You indicate run

> sudo dpkg -i ./Downloads/sqlops-linux-<version string>.deb

but the download is

> sqlops-linux-0.27.3.tar.gz

I replaced <version string> by 0.27.3 it did not work
I tried sudo dpkg -i ./Downloads/sqlops-linux-0.27.3.tar.gz it did not help
I extracted and tried sudo dpkg -i ./Downloads/sqlops-linux-x64 I get an error message error: archive './Downloads/sqlops-linux-x64' is not a regular file
 
I replaced tar.gz with deb it did not work
Can you please tell me what is needed to be d

Steps to Reproduce:
1- click on the the link provided in the url mentioned above
2- A file named sqlops-linux-0.27.3.tar.gz is downloaded and not a .deb extension
3- tried to run the command 
sudo dpkg -i ./Downloads/sqlops-linux
with all different combinations but unfortuantely is not going through

**Comment by MattIrv** [comment]
Thanks for reporting this @eliassal, it looks like the link in the docs is incorrect. This should be the right link: https://go.microsoft.com/fwlink/?linkid=870842, please try downloading that file and then following the instructions as normal

**Comment by eliassal** [comment]
Thanks, much better, setup went through. 1 question, 1st things I do when I seyup sql on windows, I go the server > properties > Database settings and change DB and log folders to other drives. I connected to my sql2017 from SSMS 16 and 17. On sqlops on windows, I noticed that default location is 

> /var/opt/mssq/data

 which is greyed out.
When I do the same thing in  SSMS 16, I get something very strange "C:\..." as if I was on a windows platform

**Comment by eliassal** [comment]
I forgot the question, so how can I change folder location of logs and Dbs in sql2017 on linux
Thanks

**Comment by kevcunnane** [comment]
A couple of things to answer this:

**Which tools you need**
- For SSMS, you need to use version [17 or later](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms) rather than older versions. Support for SQL Server on Linux was added in the 2017 timeframe, hence older (16.x or SSMS for SQL 2012/2014) versions do not have support. If you do this you'll see the correct Linux paths as expected
- For SQLOps I'm not sure which part of the tool you're using to see the location, but currently it doesn't support altering database properties.

**How to change default directory**
I'd recommend trying using the latest SSMS or using the [mssql-conf](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-mssql-conf#datadir) commandline utility and the relevant instructions for that. I believe the latest SSMS should work, but mssql-conf definitely does.

**Comment by eliassal** [comment]
I am using SSMS 17, latest update on Linux and windows. Sorry, it is not working on both
![ssmssql17-win](https://user-images.githubusercontent.com/8447864/38272709-51c2ffb8-378a-11e8-9e92-637615490aff.png)
![ssmssql17-win_002](https://user-images.githubusercontent.com/8447864/38272715-55c214fa-378a-11e8-99aa-332d7eea0542.png)
![ssmssql17-linux](https://user-images.githubusercontent.com/8447864/38272741-6c0a6e7e-378a-11e8-9381-4672956a491b.png)

**Comment by yualan** [comment]
https://docs.microsoft.com/en-us/sql/sql-operations-studio/download

Linux Download instructions have been updated for deb, rpm, and tar.gz. Original issue should be resolved.
