### ISSUE TITLE
sp_help [table] not showing constraints

### ISSUE THREAD

**Issue by Ryukote** [Microsoft/sqlopsstudio#1047]
When I run sp_help [table] (I made ALT+F1 shortkey for it) I see all info, but everything that is connected to the constraints is empty ("table is referenced by foreign key" for example). When I do the same in SSMS I can see all constraint information (yes, I am doing this on the same DB).

I have tried with all tables that crossed my mind (we have really A LOT of tables on the work so I don't intend to check them all).

**Comment by kevcunnane** [comment]
This is interesting. What happens when you run this command manually, e.g. type in `sp_help [table]` and execute? The code in both tools should be the same in that they generate the syntax and run the command. When I run it against Wide World Importers, I see constraints information when present. 

Also can you ensure you're running the latest update (0.27.3)? I know we fixed some issues in rendering tables, and I'm wondering if that could affect this.

For what it's worth, here's my output against the `Purchasing.PurchaseOrderLines` table. Note the messages output too since this might help diagnosing this:

Query - select `[Purchasing].[PurchaseOrderLines]` and execute
```sql
SELECT TOP (1000) [PurchaseOrderLineID]
      ,[PurchaseOrderID]
      ,[StockItemID]
      ,[OrderedOuters]
      ,[Description]
      ,[ReceivedOuters]
      ,[PackageTypeID]
      ,[ExpectedUnitPricePerOuter]
      ,[LastReceiptDate]
      ,[IsOrderLineFinalized]
      ,[LastEditedBy]
      ,[LastEditedWhen]
  FROM [keep_kc_WideWorldImporters].[Purchasing].[PurchaseOrderLines]
```

Indexes table:
![image](https://user-images.githubusercontent.com/10819925/38266513-ba00d99a-372d-11e8-970d-22fbb74d5cc6.png)

Constraints table:
![image](https://user-images.githubusercontent.com/10819925/38266503-b0e414f8-372d-11e8-9db9-b0a43c370fda.png)

Messages output:

> 	Started executing query "sp_help '[Purchasing].[PurchaseOrderLines]'" 
 
> 	No foreign keys reference table '[Purchasing].[PurchaseOrderLines]', or you do not have permissions on referencing tables. 
> 	No views with schema binding reference table '[Purchasing].[PurchaseOrderLines]'. 
> 	Total execution time: 00:00:00.293

**Comment by Ryukote** [comment]
Hmmm...I came back to job and now I can see constraints what I wanted to see when I use shortkey for sp_help. Don't know why but now it is working. Weird.

**Comment by kevcunnane** [comment]
OK thanks for confirming. I'm going to close this for now given it's working as expected.
