### ISSUE TITLE
App is in Applications folder but getting read only error on update. Message is hidden

### ISSUE THREAD

**Issue by ScaleOvenStove** [Microsoft/sqlopsstudio#1111]
- SQL Operations Studio Version: sqlops 0.26.7 (723c7cb3bfd80d87fc8a1141632089cd4808495c, 2018-02-16T21:17:29.202Z)
- OS Version: Darwin x64 17.4.0
- Extensions: none
---

Steps to Reproduce:

1. Check for updates
2. Error shows up, error is hidden, see attached [https://www.dropbox.com/s/hcd50ooiqoaq65k/Screenshot%202018-04-10%2009.36.57.png?dl=0](url)
3. App is in the  Applications folder, not a read only volume, so the error doesn't make sense. 

Cannot update while running on a read-only volume. The application is on a read-only volume. Please move the application and try again. If you're on macOS Sierra or later, you'll need to move the application out of the Downloads directory. See https://github.com/Squirrel/Squirrel.Mac/issues/182 for more information.

**Comment by MattIrv** [comment]
@ScaleOvenStove this is happening because of a bug in how we used to distribute updates for Mac. See https://github.com/Microsoft/sqlopsstudio/issues/732 for details

To fix it, you can either open Finder and drag SQL Operations Studio out of your Applications folder and then back into it, or you can open Terminal and run `xattr -d com.apple.quarantine /Applications/SQL\ Operations\ Studio.app/` and then relaunch

The bug where the message is hidden will be fixed in our April release

**Comment by ScaleOvenStove** [comment]
Hey @MattIrv running the command worked. Thanks for the response.

**Comment by briancrink** [comment]
@MattIrv Thanks, worked for Geektool
