### ISSUE TITLE
Figure out an alternative to Slickgrid

### ISSUE THREAD

**Issue by anthonydresser** [Microsoft/sqlopsstudio#1160]
Slickgrid is not looking at building in accessibility (and it's also not built correctly to be 100% accessible) https://github.com/6pac/SlickGrid/issues/37 and therefore we will continue to have accessibility problems with slickgrid going forward.

We should discuss and figure out what the best option is; either building our own grid library, or adopting a different one that is more accessible.

**Comment by kburtram** [comment]
@anthonydresser is it possible to get a list of example accessibility bugs in SlickGrid that are impacting us passing C-level testing?  

Also, do you suspect it may be easier to fix the accessibility issues in SlickGrid ourselves, and perhaps try to contribute them back upstream, instead of a adopting or building an alternative?

**Comment by anthonydresser** [comment]
Should I create new issues here for them? Since they are internal..

Also how they want it to work would require a completely different different structure than what slickgrid does, so I'm not sure we could pass with just contributing back or using a plugin. The problem is that modern browsers handle screen reading properly for tables only if you use table/tr/td, otherwise it reads tables very weirdly, which I'm not sure will pass their requirements.
