### ISSUE TITLE
Truncate keyword is not handled properly

### ISSUE THREAD

**Issue by khaale** [Microsoft/sqlopsstudio#131]
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce:
1. Open SQL Operations Studio
2. Connect to database (MSSQL)
3. Open New Query
4. Type `truncate table`
5. Try use intellisense to get a list of available tables

Expected results: `truncate` highlighted as a key word, intellisense works.
Actual  results: `truncate` is not highlighted, intellesense does not work.

**Comment by kburtram** [comment]
I sent a PR to fix the colorization issue, but as @arinwt mentioned the table name completion also doesn't work in SSMS.  We use the same T-SQL parser so that would be an issue we'd want to fixed "upstream" and pickup in T-SQL parser refresh.  I'll open an internal bug against that component for that aspect of this bug.
