### ISSUE TITLE
How to close Messages?

### ISSUE THREAD

**Issue by bigdatamoore** [Microsoft/sqlopsstudio#134]
How do you close the Messages pane after running a set of SQL commands?

**Comment by kburtram** [comment]
@bigdatamoore we currently don't have the ability to close the results\message pane once a query has been executed.  We have this on our short-term roadmap, likely for Dec. or Jan release.

**Comment by bigdatamoore** [comment]
Ok thanks. I was scratching my head how to do this.  Also being able to change the font in the messages tab would be good.

**Comment by bciesielski** [comment]
@bigdatamoore @kburtram 
Not sure if it's what you are looking for, but you can actually set a keyboard shortcut for the "Toggle Query Results" (I can't tell since when the command is available in key bindings, it's available at least in February release). If you assign CTRL+R to it - you will have similar behavior to SSMS.

**Comment by kburtram** [comment]
The `Toggle Query Results` command should close the messages window.
