### ISSUE TITLE
double-click not selecting @ in variable name

### ISSUE THREAD

**Issue by gbritton1** [Microsoft/sqlopsstudio#143]
SQL Operations Studio Version: 0.23.6

Steps to Reproduce:
DECLARE @var int;

double-click on @var, only 'var' is selected

**Comment by bvogelzang** [comment]
You can fix this by removing the `@` character in the `editor.wordSeparators` setting. I would agree that this should probably be excluded by default though.

![word-separators](https://user-images.githubusercontent.com/67076/33036123-27e8ed98-cdf3-11e7-99f3-288022ac472d.png)

**Comment by gbritton1** [comment]
that worked. thanks!

**Comment by kevcunnane** [comment]
Thanks folks. I've reached out to the VSCode team to see if we can override this on a per-language basis. Ideally we'd just handle the fact SQL uses the `@var` pattern but most other languages treat this separately. Will keep the issue open until we hear back. We could override the default if necessary, but I'd prefer a more targeted fix.

**Comment by gbritton1** [comment]
FWIW Python uses @ as the first character of a decorator name

**Comment by kevcunnane** [comment]
I've created https://github.com/Microsoft/vscode/issues/39218 as a tracking issue for this. Ideally we should be doing this on a per-language basis rather than changing a global default. We can still consider changing this for all of Operations Studio but I think the "correct" solution is in that issue and is upstream of Ops Studio.

**Comment by kburtram** [comment]
Please also investigate the `'$.` issue discussed in https://github.com/Microsoft/sqlopsstudio/issues/224 when resolving this issue.
