### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by joaopsf** [Microsoft/sqlopsstudio#1478]
I can not connect to sqlserver through mac. I need help. It seems to me that the problem is on port 1433.

![screen shot 2018-05-23 at 16 56 48](https://user-images.githubusercontent.com/2164695/40447929-6dc06d44-5eaa-11e8-8fc9-6e4183bb1fe4.png)

**Comment by kevcunnane** [comment]
I see you’re trying to connect to local host. Are you running SQL Server on docker? If so I’d suggest following the steps to connect from outside the container in the [documentation](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-linux-2017). Running ifconfig should provide the correct IP address to use. It’s also important to verify the port is mapped to 1433. Otherwise you would need to append the port number as “ipaddress,port” to connect.

**Comment by kburtram** [comment]
The connection code used the .Net SqlClient driver and SQL Ops doesn't really handle the connection at the network level.  Please look at @kevcunnane suggestion to troubleshot the SQL Server configuration.
