### ISSUE TITLE
status "Starting service" is not going away even after the service is started

### ISSUE THREAD

**Issue by alanrenmsft** [Microsoft/sqlopsstudio#1681]
- SQL Operations Studio Version:
master branch as of 6/19/2018

![image](https://user-images.githubusercontent.com/13777222/41627361-e29d39be-73d4-11e8-92bf-8df75519df17.png)

**Comment by MattIrv** [comment]
It looks like this happens if you don't have the latest version of the data protocol client installed after the recent [version update](https://github.com/Microsoft/sqlopsstudio/pull/1648/files). To fix it, you can rerun `yarn` to install the latest version.

Unfortunately the error gets swallowed by our `vscode-languageclient` package, which is why there was no indication of a problem except for "starting service" staying there. The latest `vscode-languageclient` version would have logged it at least, but updating would probably take a lot of work.

**Comment by alanrenmsft** [comment]
I can confirm after running yarn solved the problem.
