### ISSUE TITLE
Functional Insert button 

### ISSUE THREAD

**Issue by Kokkie-continues** [Microsoft/sqlopsstudio#1701]
- SQL Operations Studio Version: 0.30.6

The Insert button of the keyboard doesn't have any functionality yet. 
It would be nice if it would be used to overwrite the code.

**Comment by kburtram** [comment]
@Kokkie-continues we typically defer to the VS Code team for core editor functionality.  For some reason they've decided not to provide an "overwrite mode".  This issue is tracking the request in the upstream repo https://github.com/Microsoft/vscode/issues/1012.

There is a VS Code extension you can install in SQL Ops Studio to enable this behavior.  To do this, please use the following steps.

1.  Go to https://marketplace.visualstudio.com/items?itemName=adammaras.overtype and click the `Download Extension` link under `Resources` on the right-side of the page.
2. Save the VSIX file locally
3. Execute the `Install Extension from VSIX Package` command from the File menu and select the VSIX file.

Hope that helps.  If VS Code enables this feature upstream we'll pick it up in a subsequent release.

**Comment by Kokkie-continues** [comment]
Super, thanks a lot!
