### ISSUE TITLE
Extensibility: Combining Explorer and Source Control Widgets into one Widget

### ISSUE THREAD

**Issue by JASM2007** [Microsoft/sqlopsstudio#1751]
- SQL Operations Studio Version: 0.30.6

Combining the Explorer and Source Control Widgets into one Widget so that you could see a change that the user needs to check in and show changes/resolve conflicts without switch between widgets.

**Comment by kevcunnane** [comment]
This is behavior we inherit from Visual Studio Code. I believe they've made improvements in context-menu actions and ability to see status using color coding in recent releases. It's likely we will pick these improvements up in future merges. However I'd encourage you to open any issues that aren't already covered in the Visual Studio Code repository, since it's a key improvement area for them and they've been pretty responsive to suggestions around this.

**Comment by JASM2007** [comment]
Thank you for the quick response!

Sorry I don't know anything about the Visual Studio Code back-end I am a SQL Developer - the coding language I know/use are limited.  Additional Context: My team and I were talking and we think that if in SQL Operations Studio could Explorer and Source Control Widgets into one Widget that would look similar to the Extensions Widget that currently exists. You can see there is a split between "Installed" and "Marketplace" in the screen shot below. So that explorer tab and the Source Control tab could be seen in the same window/widget. I can post this in the Visual Studio Code repository if that's where is suppose to go. Can you provide a link to that repository so I make sure it get posted in the correct location? 
 
![image](https://user-images.githubusercontent.com/40634806/41994275-ee2d350c-7a1b-11e8-8d6a-f15368ac7611.png)
