### ISSUE TITLE
Messages window is showing error even after connecting to server

### ISSUE THREAD

**Issue by lakshmanmadala** [Microsoft/sqlopsstudio#1828]
- SQL Operations Studio Version:

Steps to Reproduce: 
1. Create a Stored procedure
2. Try Executing Stored Procedure with out connecting to server
[Issue 1]: "Executing Query" message and spinner appear in messages window along with error message
3. Connect to server with correct credentials
[Issue 2]: Error Message is still displayed even though stored procedure executed with out any errors

![image](https://user-images.githubusercontent.com/9732900/42223856-c3284060-7ea6-11e8-8a21-22e1d3a40df3.png)

**Comment by alanrenmsft** [comment]
@lakshmanmadala , here is what i tried:
1. locate an existing stored proc and click the 'Script as Execute' item in the context menu
2. a new window opens, click 'Disconnect' button in the toolbar to disconnect the connection
3. click 'Run' button

instead of the messages you saw, the connection dialog pops up for me.

Please let me know if your steps are different...

Thanks
Alan

**Comment by alanrenmsft** [comment]
@lakshmanmadala  I am closing the issue for now, please reactivate it if you find it not working as expected.
