### ISSUE TITLE
File saved in SSMS has illegal characters

### ISSUE THREAD

**Issue by datawesthmn** [Microsoft/sqlopsstudio#1849]
- SQL Operations Studio Version:
Version 0.30.6
Commit df7e3ec7d52a82febee5b597a1019cabf021b883
Date 2018-06-19T21:45:43.589Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:
When I open a .sql-file saved in SSMS and the file contains special characters like æøå(Norwegian "ae", "oe" and "a With ring") the characters are not displayed correctly and sqlops gives error message

**Comment by alanrenmsft** [comment]
@datawesthmn this is because SQL Ops Studio couldn't figure out the encoding of the file. SQL Ops Studio inherits the editor feature from VSCode. VSCode has an encoding auto-detection feature, but it is off by default, I turned it on and gave it a try but it is not working with the example you provided here. :(  here is the issue in VSCode repo: https://github.com/Microsoft/vscode/issues/51125. unfortunately we will have to wait until they fix the issue.

So for now, in order to have SQL Ops Studio show the contents correctly, you can either save the file with UTF-8 (the default encoding used by SQL Ops Studio) encoding in SSMS or you will have to tell SQL Ops Studio to open file with a specific encoding.

Please follow these steps to find the encoding of the file or save the file with UTF-8 encoding
1. Open the file in SSMS
2. Open the "Save As" dialog from the SSMS main menu: File->"Save xxxx As..."
3. Click the down arrow next to the Save button and choose "Save with Encoding..."
You will see the encoding used by SSMS for your file in the "Advanced Save Options" dialog.

![image](https://user-images.githubusercontent.com/13777222/44288773-4b43ed80-a226-11e8-9511-ad651886a59e.png)


There are 2 ways of making SQL Ops Studio load files using specific encoding

1. Edit the global setting:
   a. Open Command Palette (Main menu: View->Command Palette)
   b. Type "Open User Settings" in the text box and it will open the user settings editor, Search for "files.encoding" and update with the desired encoding.
   c. Save and reload SQL Ops Studio, now your file should be displayed properly.

Or

2. Open file with encoding:
   a. Open the file in SQL Ops Studio
   b. Open Command Palette (Main menu: View->Command Palette)
   c. Type "Change File Encoding", select it and then choose "Reopen with Encoding"
now you can pick the encoding you want...

Hope this helps.
