### ISSUE TITLE
CodeSignSummary.md

### ISSUE THREAD

**Issue by matt40k** [Microsoft/sqlopsstudio#20]
- SQL Operations Studio Version: 0.23.6.0

Steps to Reproduce:
Within the main build contains CodeSignSummary.md. Don't believe this should be in the program directory

**Comment by kevcunnane** [comment]
@MattIrv perhaps you could take a look at this?

**Comment by MattIrv** [comment]
Thanks for reporting this. You're right that the file shouldn't be there, but we accidentally included it when signing the build.

I just updated our build process so that it won't include the file anymore, so I'll close this bug now. If it somehow returns in a future release, please feel free to reopen this issue.
