### ISSUE TITLE
no such file or directory '/.config/.sqlops/Azure Accounts'

### ISSUE THREAD

**Issue by NiurenZhu** [Microsoft/sqlopsstudio#213]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-05T22:46:14.815Z)
- OS Version: Linux x64 4.4.0-101-generic
---

Steps to Reproduce:
starting error:
[Extension Host] Initialization of Azure account extension storage failed: Error: ENOENT: no such file or directory, mkdir '/home/niurenzhu/.config/.sqlops/Azure Accounts'
In fact, exits folder /home/niurenzhu/.config/sqlops/

**Comment by erickangMSFT** [comment]
@NiurenZhu Can you elaborate how you got this error? Are you trying to load VS code extension in SQL Ops Studio?

**Comment by NiurenZhu** [comment]
This error occurs every time it runs.
![screenshot from 2017-11-28 20 07 50](https://user-images.githubusercontent.com/13265783/33319017-ddd55c4c-d477-11e7-8862-9e41fae1f02e.png)

**Comment by kevcunnane** [comment]
So these issues are unrelated. The Azure error is always logged (we disabled this but still have some code that logs this error). The real issue is the tools service not starting.

What Linux distribution are you running? We should work on most but have the list of supported distros at https://docs.microsoft.com/en-us/sql/sql-operations-studio/download#get-includename-sosincludesname-sos-shortmd-for-linux

**Comment by NiurenZhu** [comment]
My system is "elementary os", it built on "Ubuntu 16.04.3 LTS".
![screenshot from 2017-11-29 19 32 56](https://user-images.githubusercontent.com/13265783/33374277-7352ea82-d540-11e7-9064-4e6d84923b59.png)

**Comment by kevcunnane** [comment]
So this should work since it's Ubuntu-based. However there are some dependencies needed - we'll be including these once we have a .deb / .rpt installer but for now this is manual. I noticed on the download page it's missing some of these. We're working with doc folks to fix that.

Can you let me know if installing the below dependencies resolves the issue?

```bash
sudo apt-get install libxss1

sudo apt install libgconf-2-4

sudo apt install libunwind8
```

**Comment by NiurenZhu** [comment]
It's running successfully. Thank you.

**Comment by kburtram** [comment]
Closing as resolved.  Once we have a .DEB package these dependencies will be installed automatically.
