### ISSUE TITLE
Extensibility: Getting connection string

### ISSUE THREAD

**Issue by aaomidi** [Microsoft/sqlopsstudio#2185]
When using the connection api namespace, getConnectionString returns an undefined string.

For example:

`sqlops.connection.getConnectionString(connectionId, true)` returns an undefined value.

**Comment by aaomidi** [comment]
I've had to work around that here: https://github.com/Microsoft/sqlopsstudio/blob/c058439c929b9a9f5d8d1deba33cdd97b47cb344/extensions/import/src/wizard/pages/summaryPage.ts#L133-L146

**Comment by MattIrv** [comment]
I investigated this a bit and just talked to Karl about it. The method expects a URI right now, not a connection ID (despite the parameter) because the getUriForConnection method doesn't work right for editor connections. The real bug here is that getUriForConnection should be fixed to always return a URI corresponding to an active connection.
