### ISSUE TITLE
Seti Icons are Default for all File Types

### ISSUE THREAD

**Issue by breadboi** [Microsoft/sqlopsstudio#2196]
- SQL Operations Studio Version:
Version 0.32.3-insider
Commit 220e4feb1d65de98fd7f872a699b47b6f18d7bc7
Date 2018-08-06T12:19:36.303Z
VS Code 1.23.1
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:
• Fresh install of the version shown above.
• Click on the Explorer button on the left hand side and open a folder.
• Almost all files in the folder are missing Seti Icons.

This feature is working correctly for me in the July release, but for the latest insider release, it is not. For your reference, I've included a screenshot of a few file types that aren't having their Seti Icon displayed correctly alongside some that are displayed correctly.

Please let me know if I can provide additional information.
![seti icon issue](https://user-images.githubusercontent.com/32111055/43900124-808d0946-9ba9-11e8-99dd-e4708293b7c3.PNG)

**Comment by Blindeddie** [comment]
see the following issues that might clarify this issue.. #387 and #2153. Appears this is by design.

**Comment by bcarne6** [comment]
I agree with this design choice; however, I believe that I'm still encountering a bug since my new query icon is the default Seti Icon and not the new icon in the screenshot below. 

![image](https://user-images.githubusercontent.com/32111055/43904250-cfb0b55e-9bb3-11e8-9514-64d9149a970b.png)

The main reason that I would like something other than the default Seti Icon is that when I have a folder open on the side that has example.* and example.sql files in it, I would like to be able to, at a glance, identify my .sql files.

I feel like the solution to this would be to, instead of setting everything to default, add more options to the settings for those who like the Seti Icons as is. In the below screenshot, you can see that there are only two options for icons in the settings.

![image](https://user-images.githubusercontent.com/32111055/43904465-51ae3b8a-9bb4-11e8-944a-69afd310b653.png)

**Comment by kburtram** [comment]
The icon change for SQL files is "By Design" since we've gotten negative feedback on the red DB icon previously.  We're certainly open to additional feedback for the default SQL icon, but please keep in mind this is an area where there are many different valid opinions, so we basically have to more forward with some reasonable decision.

The change shouldn't have updated the icon for other file types so I'll take a look to see if there are unintended side-effect to the change.

@breadboi the below icon is for the dashboard.  We actually have a nice icon our UX designer produced for this document type, but it wasn't displaying correctly in the dark theme, so we'll need to follow-up on that.

![image](https://user-images.githubusercontent.com/32111055/43904250-cfb0b55e-9bb3-11e8-9514-64d9149a970b.png)

Here's the proposed dashboard icon.

![icon](https://user-images.githubusercontent.com/599935/43914535-04a0be72-9bbd-11e8-9ddd-ee99d3b1f840.png)

@yualan, @breadboi does have concrete feedback which is we shouldn't use the default Seti icon for SQL files, and I'm inclined to agree.  Let's try to find another "neutral" icon for SQL files.

**Comment by kburtram** [comment]
I've sent a PR that reverts the .SQL file icon back to the DB icon, but switches the color to the default light grey.  Please let me know if there's any feedback on that proposed change.
