### ISSUE TITLE
save excel

### ISSUE THREAD

**Issue by burdier** [Microsoft/sqlopsstudio#2397]
Issue Type: <b>Bug</b>

when i try save result as excel when select multple column not work. 

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.86GB (1.09GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by MattIrv** [comment]
@burdier it looks like you're using an outdated version of Ops Studio since the latest is 0.32.8. We fixed some issues in this area for the latest release so can you update and see if it resolves the problem? 

I do see an issue in the latest release where the export buttons on the right side of the query results sometimes don't work (see #2384), but if you right click on the selected cells and choose "Save As Excel" it should work

**Comment by burdier** [comment]
Sorry, it's not a bug, I was wrong on the way to do it.
