### ISSUE TITLE
Query results grid styles have significantly changed

### ISSUE THREAD

**Issue by kburtram** [Microsoft/sqlopsstudio#2437]
- SQL Operations Studio Version: `master`

The Query results grid styles are significantly different in `master` than we've shipped in previous releases.  The below screenshot highlights some of these differences.  Some key differences are:

1. The selection foreground and background colors are different
2. The is now a row highlight background when hovering a row
3. Column widths are more narrow
4. Font is a little lighter weight
5. Grid line colors are different
6. Selection dotted-line doesn't align with grid lines

> Note if any changes are intentional let's set up a design review meeting to discuss the rationale.

![image](https://user-images.githubusercontent.com/599935/45179924-b4d46d80-b1ce-11e8-9c20-444c20c4810d.png)

**Comment by MattIrv** [comment]
A couple more issues here shown in the screenshots below (if you want me to track in a separate bug I can open one)

- The messages pane is much bigger by default than it used to be
- If you need to scroll to see all the results the last one gets cut off by the messages pane

Old:
![Old results grid showing a small messages pane at the bottom and no results cut off](https://user-images.githubusercontent.com/3758704/45183956-60cf8600-b1da-11e8-97fc-aaf902c7dec4.png)

New:
![New results grid showing a huge messages pane and results grid cut off](https://user-images.githubusercontent.com/3758704/45183986-7644b000-b1da-11e8-9507-da0b77673c12.png)

**Comment by anthonydresser** [comment]
@MattIrv the link number link isn't fixable, since before that string wasn't localize, where as now it is. When that string is localize there's no way to isolate the "line x" part of the string. I can certainly change the color of the line to be blue or something more obvious if that would fix it.

Regarding the colors, they are now coming from the theme (which they weren't before) and so they share a consistant color theme with the other list like controls (tree, list, table).

![image](https://user-images.githubusercontent.com/4324725/45236028-88345a80-b28f-11e8-89fe-8a13b9c017ce.png)
![image](https://user-images.githubusercontent.com/4324725/45236041-91252c00-b28f-11e8-9555-73c800ab18b1.png)

So if we want to change the colors back to what they were, we should be changing the theme colors for tables/lists/trees.

**Comment by kburtram** [comment]
@anthonydresser let's do a design review for the grid colors Monday morning.  I prefer the previous color scheme for the grid, but I'm not sure we want to change the whole theme.  It may be better to have special styles just for the query results grid.  Let's look at what the impact of changing the theme will be.

**Comment by kburtram** [comment]
I think this is a related query editor regressions (not style related though) https://github.com/Microsoft/sqlopsstudio/issues/2464.

**Comment by kburtram** [comment]
Based on UX review the current behavior (with pending bug fixes) is fine for September.  I open this issue to track a follow-up suggestion https://github.com/Microsoft/sqlopsstudio/issues/2522.
