### ISSUE TITLE
Intelisense does not recognize CREATE OR ALTER syntax.

### ISSUE THREAD

**Issue by ArmandoLacerda** [Microsoft/sqlopsstudio#264]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299
---

Intelisense does not recognize CREATE OR ALTER syntax.

If you type
Create or Alter View VW
as
Select 1;
go;

Intelisense will mark everything in red. If you run the statement it will execute successfully, though. 

Steps to Reproduce:

1. Type the statement as described above.
2.

**Comment by kevcunnane** [comment]
I'm struggling to reproduce this with this example. If I follow exactly I get an error that no column was specified (see below), and it fails when executing.

![image](https://user-images.githubusercontent.com/10819925/33464775-f9435d58-d5f8-11e7-808d-24e0c966a2ba.png)

Using a more regular view body like `select * from sys.tables` intellisense shows no errors with `CREATE OR ALTER` syntax and execution works. There are a few scenarios where I can get intellisense to show errors but still execute successfully, but these also apply to standard CREATE syntax and are strange edge cases (e.g. if you remove the semi-colon after 1, you end up with a column called `GO` in your view).

Can you provide a different example where this happens, and the T-SQL statement is valid? As of now I'll mark this as "more info" since it needs more information before we can understand the issue and look for a fix.

**Comment by ArmandoLacerda** [comment]
Hi @kevcunnane, sorry typing an incomplete code. While typing the issue I forgot the name the column. My bad.

Here are two screenshots. The first shows the issue and the second comments out the part intelisense can't understand. Both statements execute well, though.

The issue:
![image](https://user-images.githubusercontent.com/15189226/33489125-da43ce78-d667-11e7-9044-61d74652f680.png)

Just the alter statement:
![image](https://user-images.githubusercontent.com/15189226/33489176-f9d5dc36-d667-11e7-832e-ccd44bc90a56.png)

Hope this helps. Let me know if you need any more info.

**Comment by llali** [comment]
@kevcunnane I recently fixed this bug. If you're using the latest build, hopefully you won't be able to repro it. It does repro in the release build.

**Comment by ArmandoLacerda** [comment]
It good to know, @llali. I download it 2 days ago and I am loving the product and happy to share what I find as I use it.

Is the new build with this fix available for download?

Thanks.

**Comment by kevcunnane** [comment]
Leila was incorrect in that her fix is for Peek Definition. I'm still not able to reproduce this. Can you show me what the error is in the `Problems` panel? `View` -> `Problems` will open this.

**Comment by ArmandoLacerda** [comment]
I see, @kevcunnane . 

One thing I've just noticed is: when I am not connected I don't see the Intelisense error. It only shows when I am connected to either on-prem SQL 2016/2017 or to Azure SQL DB.

Not connected:
![image](https://user-images.githubusercontent.com/15189226/33507349-1d363298-d6a9-11e7-91e0-86eb7e3325a6.png)

Connected:
![image](https://user-images.githubusercontent.com/15189226/33507537-1b6ff7c2-d6aa-11e7-96dc-ba400e9adc24.png)

**Comment by kburtram** [comment]
I am not able to reproduce the syntax errors on the current release.  Please reactive if the issue persists.

![screen shot 2018-07-16 at 10 05 19 am](https://user-images.githubusercontent.com/599935/42772636-e4b8eb6a-88df-11e8-819e-431c67c49d8b.png)
