### ISSUE TITLE
Database dashboard refresh doesn't reflect changes to database properties or object list

### ISSUE THREAD

**Issue by guzmanda** [Microsoft/sqlopsstudio#280]
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce:

- right-click on a user database in object explorer and select Manage
- click the New Query task button
- execute DDL script to change the database compatibility level and create a new table:
    ALTER DATABASE WideWorldImporters SET COMPATIBILITY_LEVEL = 140;
    CREATE TABLE dbo.repro(col1 int);
- click on the database dashboard tab
- click on the ellipsis button on the database dashboard pane and select Refresh 

Actual behavior: the database properties remain unchanged and the new object is not listed in the search box.

**Comment by anthonydresser** [comment]
@kburtram this sounds like a problem in the extension service, most likely what is happening is the SMO object that is created in order to get the metadata is not being told to refresh on subsequent requests so it's just returning the same data every time. You would have more information on this though. In any case the dashboard is attempting to refresh but the extension is returning the same data.

**Comment by anthonydresser** [comment]
In terms of the properties part. This seems to be working for me, it must have been fixed at some point since this issue was created. @guzmanda can you confirm?

**Comment by anthonydresser** [comment]
The object explorer seems to be fixed as well.

**Comment by guzmanda** [comment]
@anthonydresser, I confirmed this refresh issue no longer exists. Tested using:

Version 0.26.7
Commit 723c7cb3bfd80d87fc8a1141632089cd4808495c
Date 2018-02-16T21:34:47.034Z
Shell 1.7.11
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Thanks for following up.
