### ISSUE TITLE
User Prefrences for Keyword, intellisense, and datatypecasing ignored

### ISSUE THREAD

**Issue by sebcruz** [Microsoft/sqlopsstudio#291]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299
---

User preferences for font case are ignored.

Steps to Reproduce:

1. Edit the following user preferences to be "lowercase"
    "mssql.format.keywordCasing": "lowercase",
    "workbench.colorTheme": "Abyss",
    "mssql.format.datatypeCasing": "lowercase",
    "sql.intelliSense.lowerCaseSuggestions": true
2. Save preferences
3. Restart SQL Ops

**Comment by kburtram** [comment]
@sebcruz there is a bug where the `sql.intelliSense.lowerCaseSuggestions` is only recognized as `mssql.intelliSense.lowerCaseSuggestions`,  This will be fixed in an upcoming release to use `sql` namespace, but current workaround is to use `mssql`.  Are the other `mssql.format` options also not work as expected?

**Comment by sebcruz** [comment]
Thanks kburtram.  I added "mssql.format.placeCommasBeforeNextStatement": true to my preferences and the editor respected the setting and will format sql appropriately so perhaps the bug impacts just some of the mssql namespace preferences.
