### ISSUE TITLE
The database is not deleted!

### ISSUE THREAD

**Issue by emin-karadag** [Microsoft/sqlopsstudio#309]
**Hello,

I can not delete when I want to delete a database I created**

- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299
---

**Comment by SebastianPfliegel** [comment]
How do you want to delete the database? Currently SQLOps only supports deleting the database with a DROP DATABASE SQL statement. There's no way to do this with the GUI at the moment (like right clicking on a DB ...). If you use the DROP DATABASE statement, notice that it may fail due to the database being currently in use. That is a regular behaviour.

**Comment by wsmelton** [comment]
I would say providing the ability to do some common, quick task via the Command Palette would be awesome. Such as dropping a database.

So you would:
1. CTRL + P
2. Type Drop
3. a list of options comes up like `Drop: Database`
4. A prompt would then come asking you for the object name, in this case a database.
5. Internally it would simply execute the DROP DATABASE command but maybe somehow also give us the option to do a "force" operation that kills all active connections.

Course I guess an extension could be written that let you do this as well.

**Comment by erickangMSFT** [comment]
@emin-karadag As Sebastian pointed out, it is mostly likely the t-sql execution issue. Please try it again after executing following statement.
 
ALTER DATABASE <DatabaseName> SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
