### ISSUE TITLE
"cannot set terminal process group (-1): Inappropriate ioctl for device"

### ISSUE THREAD

**Issue by yooakim** [Microsoft/sqlopsstudio#317]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-05T22:46:14.815Z)
- OS Version: Linux x64 4.13.0-19-generic
---

Steps to Reproduce:

1. Start terminal in Ubuntu 17.10
2. Launch `sqlops`

```
[joakim:~/sqlops-linux-x64] $ ./sqlops 
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
```

**Comment by MattIrv** [comment]
Thanks for reporting this. To clarify, SQL Ops Studio still starts and works correctly, correct? I see this message on Ubuntu as well, but the program seems to be working normally otherwise.

**Comment by R-i-c-h-B** [comment]
Same issue under Fedora 27.  Yes it starts and works no problem.  Installed as per the instructions provided.

Found that: 
> sqlops & disown 

seems to help a little (untieing it from the shell process so that closing the terminal window you launched it from doesn't shut it down), but still get the message.  

Would be nice to get it installing with a neat icon and lodged properly so that dnf can install it etc.

(loving the application though, really nice!)

**Comment by kburtram** [comment]
This is a diagnostic logging message that shouldn't have any functional side effects.  Please log a issue upstream in vscode repo if the log message is bothering you.
