### ISSUE TITLE
return focus to sql work area after run query

### ISSUE THREAD

**Issue by mfarouke** [Microsoft/sqlopsstudio#341]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299
---

Steps to Reproduce:

1.
2.

**Comment by kburtram** [comment]
This looks like a duplicate of [#19 Running query/hitting F5, query window looses focus](https://github.com/Microsoft/sqlopsstudio/issues/19).  The issue should be fixed in Dec. release planned for next week (release candidate with this fix is available at https://github.com/Microsoft/sqlopsstudio/releases/tag/v0.24.1)
