### ISSUE TITLE
"Run Current Query with Actual Plan" - add "Actual Join Type" for Adaptive Joins as in SSMS

### ISSUE THREAD

**Issue by smooth1x1** [Microsoft/sqlopsstudio#351]
- SQL Operations Studio Version: sqlops 0.24.1 (4bf9955d43966e534e8758d5749bfa18f132a6b1, 2017-12-18T19:12:07.590Z)
- OS Version: Windows_NT x64 10.0.17046
---

Steps to Reproduce:

1. "Run Current Query with Actual Plan"  for an Adaptive Join http://www.smooth1.co.uk/installs/dbinstalls.html#3.1.24

2. Need to add "Actual Join Type" for Adaptive Joins as in SSMS - http://www.smooth1.co.uk/sqlserver2017/2017_2_dbe.html#2.7.4

**Comment by JustinPealing** [comment]
Do you have the query plan XML?

**Comment by kburtram** [comment]
We'll pick up @JustinPealing's latest html-query-plan control for the February release to get this fix.

**Comment by anthonydresser** [comment]
@kburtram this should be done as of #517 not sure how to test this though...

**Comment by kburtram** [comment]
@anthonydresser yes, I think the html-query-plan refresh you did should resolve this.  I'll reassign back to myself to verify.

BTW, I saw @JustinPealing committed a few more changes since our refresh, so we should discuss how to be able to pick-up these changes more simply.  e.g. if we have any customizations we should see if we can get those pushed upstream, or otherwise eliminated.

**Comment by anthonydresser** [comment]
I'll work on making a PR upstream. Most of my changes are regarding developement process stuff in order to output the typings for the library. There no functional differences.

**Comment by kburtram** [comment]
This appears to be fixed in the July release.

![screen shot 2018-07-19 at 8 09 55 am](https://user-images.githubusercontent.com/599935/42951512-3084fcd0-8b2b-11e8-980a-0f7beab8435f.png)
