### ISSUE TITLE
When the chart viewer throws an error, unexpected behavior occurs.

### ISSUE THREAD

**Issue by martinisaksen** [Microsoft/sqlopsstudio#37]
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce:
1. Run "SELECT 1 AS A"
2. Select "View as Chart"

What I'd expect to see:
Chart viewer tab selected and count Chart Type selected.

What I see:
Stays at Results tab but Chart Viewer tab is available. I have to manually click on the tab and choose "count".

**Comment by anthonydresser** [comment]
When the chart viewer throws an error a few things can happen.

1. The tab is not navigated to automatically.
2. On subsequent re-runs, you can't open the tab all together.

At the end of the day we should properly catch errors that occur do to miss-formatted data and ensure expected behavior still occurs.

**Comment by anthonydresser** [comment]
Additionally, if on chart type change an error is thrown, it can make the chart unresponsive and require a rerun to make work again.
