### ISSUE TITLE
sp_help on ALT+F1

### ISSUE THREAD

**Issue by thiagomiranda3** [Microsoft/sqlopsstudio#441]
- SQL Operations Studio Version: 0.24.1

In SQL Management Studio, we can view the table structure by using ALT+F1 which call sp_help [table].
Can we have the same shortcut for SQL Operations Studio?

**Comment by kevcunnane** [comment]
This is supported in the December release, but the default is `Alt+F2` since `Alt+F1` was already bound. You can change this key binding and assign values for the other shortcut entries (there are 10, just like in SSMS) by opening `Keyboard Shortcuts` and editing the `workbench.action.query.shortcut1` setting.

![image](https://user-images.githubusercontent.com/10819925/34578752-fb262d64-f13a-11e7-9d19-df7d20692715.png)

![image](https://user-images.githubusercontent.com/10819925/34578763-05b1781a-f13b-11e7-9190-9b21e154dd00.png)

**Comment by thiagomiranda3** [comment]
Thanks for reply.

**Comment by R-i-c-h-B** [comment]
Hi all,
For anyone running Fedora, you may notice that Alt-F1 is already bound outside SQLOPS to pop up the 'activities overview' screen - where you see all your running windows and quick launch options.

You may have found how to disable that, and swap it out with the 'not windows' key.  You may then have found that the alt-f1 is now bound to the selectively useful 'accessibility help' rather than the more traditional context sensitive help you may be used to.

Maybe that brought you to this post.  And now you will find that ALT-F2 in Fedora brings up the run program command.  By now you have probably freed up alt-f1 away from the gnome shell, so now from the above you know how to reallocate the correct command to alt-f1 again...  

Cross platform ftw.
