### ISSUE TITLE
The connection's current state is closed. 

### ISSUE THREAD

**Issue by lvlopezg** [Microsoft/sqlopsstudio#446]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.15063
---

Steps to Reproduce:

1.If I stop of using for a few minutes, The connection to Database it's closed.
2. I don't found where to reconect o refresh the connection to the Database Engine.

**Comment by kevcunnane** [comment]
This looks like an issue I fixed in the December release. Specifically, query editor wasn’t reopening the connection if it was closed. I’d recommend updating to the December release and it should fix this for you. I’m going to close this, but please reopen / comment if this doesn’t resolve it for you.
