### ISSUE TITLE
Connection dialog start without selecting the top recent history entry

### ISSUE THREAD

**Issue by erickangMSFT** [Microsoft/sqlopsstudio#458]
- SQL Operations Studio Version:

Steps to Reproduce:

1. CTL+N to open a new query edtior.
2. Click 'Connect'

Expected: The most recent connection in the history list is selected and the connection properties of selected connection entry is populated hence use can make a connection without further interaction.

Actual: The functionality is regressed and Connection dialog does not populated connection properties for the top entry.

![image](https://user-images.githubusercontent.com/11077282/34749111-81144128-f554-11e7-9da7-0be06b3d3b56.png)

**Comment by kburtram** [comment]
@erickangMSFT I don't think the connection dialog ever worked the way you've mentioned.  I checked Dec. release and you had to explicitly select a connection from the MRU to populate the fields in that build (and this is the way I recall it being IIRC).  I think this should be marked as a suggestion instead of a regression, but I'll leave it you to confirm.

**Comment by erickangMSFT** [comment]
@kburtram thanks. suggestion is right in that case.

**Comment by kburtram** [comment]
@erickangMSFT we discussed this suggestion and generally prefer the current design where the user inputs settings for a new connection by default, and has to explicitly select an item from the MRU.
