### ISSUE TITLE
Support alt to vertical select

### ISSUE THREAD

**Issue by virtualcca** [Microsoft/sqlopsstudio#470]
- SQL Operations Studio Version:0.24.1

now sql operation studio can not press alt and vertical select
I only use notepad++ to alt process and copy to sql operation studio
can support this feature?

Steps to Reproduce:

**Comment by kevcunnane** [comment]
I'd suggest you take a look at the [Keyboard Shortcuts Reference](https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-reference) for your particular operating system. The `multi-cursor and selection` reference info is most relevant here - it's likely one of those settings matches your request.

![image](https://user-images.githubusercontent.com/10819925/34806918-a2ed4dd0-f63a-11e7-8bbe-c5f26c887a75.png)

I'm going to close this out since I believe the above reference will solve your problem, and basically all support for actions like this are pulled in from VSCode. Please reopen / comment if this doesn't turn out to be the solution.
