### ISSUE TITLE
Running Bulk Insert statements cannot find files (OSX)

### ISSUE THREAD

**Issue by drbergeron** [Microsoft/sqlopsstudio#495]
- SQL Operations Studio Version: Version 0.23.6 (0.23.6)

Steps to Reproduce:
1. create a file for bulk insert on the mac hard drive in a folder ( i used ~/Documents and /Users/<account>/Documents)
2. Try to load this data into a table
3. You'll get an error saying that it cannot find the file specified, but you can interact and open that file via terminal commands as normal.

Example:
begin tran
bulk insert some_table from '/Users/johnsmith/Documents/test.txt' with (
    FirstRow=2
)
rollback tran

Error:
Msg 4860, Level 16, State 1, Line 2
Cannot bulk load. The file "/Users/johnsmith/Documents/test.txt" does not exist. 

But from terminal i can go:
code /Users/johnsmith/Documents/test.txt

and VS Code will open that file without any issues.

**Comment by kevcunnane** [comment]
@drbergeron the issue here is that `BULK INSERT` needs to specify paths relative to the SQL Server instance running - [here's the doc on this](https://docs.microsoft.com/en-us/sql/t-sql/statements/bulk-insert-transact-sql).

> data_file must specify a valid path from the server on which SQL Server is running. If data_file is a remote file, specify the Universal Naming Convention (UNC) name. A UNC name has the form \\Systemname\ShareName\Path\FileName. For example, \\SystemX\DiskZ\Sales\update.txt.
Applies to: SQL Server 2017 CTP 1.1.
Beginning with SQL Server 2017 CTP1.1, the data_file can be in Azure blob storage.

If you are running against a remote server that means it needs to be in a path on that server, or a network-accessible drive. For Docker instances that means you would likely need to mount a local directory so it's available in docker - see [here](https://stackoverflow.com/questions/23439126/how-to-mount-host-directory-in-docker-container) for an example. A quick check online doesn't show too many examples of this, I suspect because most people are using BCP to do this.

I'm going to close this issue out as it's T-SQL related and I believe the guidance above should help you get unblocked.
