### ISSUE TITLE
The HotExit doesn’t work for me

### ISSUE THREAD

**Issue by waleed66** [Microsoft/sqlopsstudio#520]
The HotExit doesn’t work for me. It appeared to work for the first time I upgraded and put the settings.
But second time around (exit/open) – I keep getting prompted to save open files. I guess still buggy?

**Comment by kevcunnane** [comment]
Have you set the `files.hotExit` setting to `onExit` or `onExitAndWindowClose`? This feature is off by default. 
![image](https://user-images.githubusercontent.com/10819925/35129229-790213bc-fc6f-11e7-8fbb-d2bf58cf541f.png)

**Comment by kburtram** [comment]
The HotExit feature has been particularly buggy due to incompatibilities with VS Code shell and our custom SQL Query Editor implementation.  We haven't seen a bug yet where users are prompted to Save even when feature is turned-on yet (though it wouldn't surprise me).

I would recommend using the `onExitAndWindowClose` setting which seems to behave how most people would expect in my opinion.  `onExit` behaves a little strange to me on macOS since you can close the main window without actually exiting the app which bypasses the HotExit code path.

**Comment by kburtram** [comment]
Closing out older issues that don't have a pending request.  Please reactive if there's still anything we should look at for this issue.
