### ISSUE TITLE
Cannot restore db from backup (.bak file) MacOSX - High Sierra

### ISSUE THREAD

**Issue by craigdetter** [Microsoft/sqlopsstudio#565]
- SQL Operations Studio Version: sqlops 0.25.4 (475904d2b2e32e7f91284c199234399ee7d5d418, 2018-01-16T20:38:17.482Z)
- OS Version: Darwin x64 17.3.0
---
I love SQL Operations Studio, but I am using it on MacOSX - High Sierra v.10.13.2, cannot get Restore working.

Steps to Reproduce:

1. Click on "Restore" from Server Dashboard, 
2a. Select backup file, either enter file path in the path input box, or  
2b. Click on [...] also cannot select local path. 

SQL Ops Studio keeps wanting to prepend: D:\RDSDBDATA\BACKUP to the file path name, which is a Windows prefix.

<img width="1168" alt="screen shot 2018-01-27 at 3 25 17 pm" src="https://user-images.githubusercontent.com/15794819/35476520-f5c241f2-0376-11e8-851d-f78dc21143dd.png">

**Comment by MattIrv** [comment]
@craigdetter sorry for the delay in responding but it looks like you're trying to use a path on your client machine while our backup/restore dialogs expect remote paths on the server machine. In order to restore using the backup file you'll have to transfer the file to the server and then browse to it.

I just opened #941 to track improving the user experience in this area to make it more clear where the path is coming from. If this explains the problem you're having, I'll close this issue. Thanks!
