### ISSUE TITLE
Keep connection and selected database when opening new query tabs

### ISSUE THREAD

**Issue by anton-johansson** [Microsoft/sqlopsstudio#6]
Before we get to the issue, I've been waiting for a tool like this for quite some time, I'm very excited! Looks very nice so far!

### SQL Operations Studio version
Version 0.23.6
Commit 8a3011756318a2ded1e6e84332230a2b2bf9c544
Date 2017-11-05T22:46:14.815Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

### Steps to Reproduce
 * Connect to a database server
 * Open a new query
 * Select a database
 * Open a new query (`Ctrl + N`)

I would very much like if the connection and selected database would still be there in the new query tab (similar to what Management Studio does)!

**Comment by kevcunnane** [comment]
To clarify - do you mean these should be shown in the tab title rather than `SQLQuery1`?

**Comment by Code-DJ** [comment]
Click on a Server on the sidebar
Hit Ctrl+N
type a query
Hit F5
It does not run the query, instead asks for a connection. On SSMS, it runs it against the selected Server in step 1.
While on the query screen, hit Ctrl+N again
Now write another query and hit F5
It again asks for a connection

**Comment by kevcunnane** [comment]
@Code-DJ excellent, that clarifies the ask. Improving context-based commands (e.g. Ctrl+N detecting the active connection in object explorer) is something we plan to do. This seems like a good place to start on that.

**Comment by anton-johansson** [comment]
Thanks, @Code-DJ, that's exactly what I meant. :)

**Comment by nalexander50** [comment]
I think this is in the same vein but I can move to a new issue if not.

I would also like to see the current connection settings persist if I press Ctrl-N in a query window.

To clarify:

I'm connected to MyServer\DatabaseA and writing queries in a query editor. I press Ctrl-N and a new query editor tab appears but it has no connection. I want it to still have MyServer\DatabaseA. It would be nice if it kept the connection of the tab you were just on.

Reason being, I like to keep my queries sequestered. If I'm querying a set of related tables in one tab and I need to run some unrelated queries, I always do those in a new tab to keep my workspace pristine. In SSMS, I can just use Ctrl-N and keep on querying.

---

Note: I'm not sure if SSMS is actually persisting the settings from the tab or just using the default connection. I have a sneaking suspicion it's just using the default connection. Regardless, using the default connection is enough since that's the database I'll be querying 90% of the time, hence default.

**Comment by kburtram** [comment]
@MattIrv could you please look at this issue?  Please implement as a generic "Global Current Connection" context that can be used by any global command that is executed without an explicitly implied connection.

**Comment by MattIrv** [comment]
This feature has been added and will be in the February release, so I'll close this issue. It's available now in the latest [February preview build](https://github.com/Microsoft/sqlopsstudio/releases) for anyone who is interested.
