### ISSUE TITLE
Recent Connections: "Loading..." in the recent connections list

### ISSUE THREAD

**Issue by abist** [Microsoft/sqlopsstudio#622]
I'm seeing a "Loading..." entry in the Recent Connections list

![kek](https://user-images.githubusercontent.com/6411451/35892429-1a1ec5d6-0b5e-11e8-98b5-1eba1ece3163.JPG)

**Comment by MattIrv** [comment]
I was able to repro this by triggering the "undefined" bug using a version of SQL Ops Studio before Leila's fix, attempting to connect so that the connection would be saved in my recent connections, and then opening the version that has Leila's fix.

That means this is just an artifact of using the previous buggy dev version of SQL Ops Studio. Leila's fix ensures that users won't run into the undefined bug when upgrading from January to February, so I don't think we need to do any more work here to fix this issue.

You can just delete the invalid connection from your recent history and it won't come back.

**Comment by abist** [comment]
@MattIrv I'm going to go ahead and close this issue then. If I see this again, I'll open a new issue.
