### ISSUE TITLE
More guidance with building the source code

### ISSUE THREAD

**Issue by dfalso** [Microsoft/sqlopsstudio#650]
Apologies in advance, but I didn't see anywhere else to post this. I've also searched and don't see any walkthroughs on compiling SOS. Please feel free to redirect me to a more appropriate forum for this question.

Background: I'm new to all of these tools - I'm normally a C#/SQL developer, working in VS 2015/2017.

I'm on Windows, and am trying to build locally. I've installed git/Node JS/Python, and ran the WIndows Build Tools to be safe. Attempting to run the npm.bat file, I get an error about yarn. I didn't see anywhere where yarn would have been installed. Where does it come from?
I then went and downloaded yarn, but it doesn't support Node 7.9, only >=8.0. I also couldn't find a "previous version" page for yarn downloads. This is where I'm stuck.

I assume all this needs to be run in PowerShell? It's not clear.

Finally, there was a line in the How To Contribute that makes it sound like this project can be worked on in Visual Studio 2015. If so, how? What would be the project type?

Again, thanks for any assistance. 
-Dominic

**Comment by MattIrv** [comment]
Thanks for reporting this. We recently changed the process for building SQL Ops Studio and it looks like our docs are out of date now. In the meantime, you can pretty much follow along with VS Code's build process at https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source. Essentially you can just do the following:
- Install the dependencies listed in the link above, including Node >= 8.9.1 < 9.0.0 and yarn
- Clone the SQL Ops Studio repo and go into it in a terminal/powershell window
- run `yarn`
- run `yarn run watch`

If you have any trouble with those instructions please let me know.

As far as working on the project in Visual Studio, that line in the docs is just intended to say that you need to have Visual Studio installed in order to get the required build tools. We use VS Code as our development environment

**Comment by MattIrv** [comment]
I've updated our documentation now, so please see the updated [How to Contribute page](https://github.com/Microsoft/sqlopsstudio/wiki/How-to-Contribute) for the new instructions on how to install dependencies and compile SQL Ops Studio. Thanks
