### ISSUE TITLE
Toogle Zen Mode

### ISSUE THREAD

**Issue by wsalmi** [Microsoft/sqlopsstudio#763]
- SQL Operations Studio Version: sqlops 0.26.7 (723c7cb3bfd80d87fc8a1141632089cd4808495c, 2018-02-16T21:34:47.034Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: none
---

Shortcut to "Zen Mode" does not work! (Ctrl + K, Z)

**Comment by kevcunnane** [comment]
I just verified the command works on the release version, both Windows and Mac. Note that you shouldn't hold down Ctrl when hitting Z, but can verify that it works by hitting Ctrl+Shift+P then typing in "Toggle Zen Mode" and choosing that command. That'll avoid any keybinding issues. If this doesn't work, can you please give additional information since it seems machine-specific?

**Comment by wsalmi** [comment]
I found the problem ... UX (and me)

The shortcut is represented as "CTRL + Z K" and not "CTRL + Z, K"

That way my behavior was to execute the standard adopted in VS.
I pressed CTRL + Z, released Z, and pressed K.

Thanks and sorry!

**Comment by kevcunnane** [comment]
No worries. If you have issues on this UX approach I'd suggest opening a bug at https://github.com/Microsoft/vscode/issues since we inherit this from VSCode. I'll close this bug out for now but please open future issues as you run into them.

**Comment by KoalaBear84** [comment]
I've created one as I couldn't find any related issues on vscode:
https://github.com/Microsoft/vscode/issues/51076
