### ISSUE TITLE
Leading spaces are not trimmed from server name

### ISSUE THREAD

**Issue by jaredrussell** [Microsoft/sqlopsstudio#790]
- SQL Operations Studio Version: 0.26.7

Steps to Reproduce:
1. Create a new connection
2. In the `Server name` input enter a valid server name but prefix it with a space
3. Fill in the rest of the form with valid details
4. Click connect. You will see the error message: `Cannot open server " some-server.database.windows.net" requested by the login. The login failed.`

Some additional test cases I've tried:
 - Entering a server name with a trailing space: connection succeeds suggesting it is trimmed
 - Connecting through SSMS: it appears to ignore leading spaces and connecting with one works correctly

If there is some reason that leading spaces cannot be trimmed the error message could at least be made more helpful (e.g. server not found).

**Comment by anthonydresser** [comment]
@kburtram @kevcunnane or anyone who has more knowledge than I, should trailing spaces also be trimmed?

**Comment by anthonydresser** [comment]
And should we do the same for username?

**Comment by kevcunnane** [comment]
Sooo... people have crazy names sometimes and we have to support them. For username and database name you can create with spaces. For example try creating a user `[WithSpaces   ]` and verify you need to include spaces to connect. We can't restrict it in this case. For server I'm not sure since it's basically a DNS-based lookup so we should verify.

My guess is server can be trimmed, others can't. We should consider a warning in those cases.
