### ISSUE TITLE
Feature Request: Auto Connect to current server after Script as...

### ISSUE THREAD

**Issue by barryseymour** [Microsoft/sqlopsstudio#825]
- SQL Operations Studio Version: 0.26.7

When scripting an object, opening a script from file or creating a new script, I'd like it if SQLOps automatically connected to the current server.

Steps to Reproduce:
#1: Altering a stored procedure
Open Servers
Locate a stored procedure 
Right-click, select 'Script as Alter'
Run Script - CONNECTION appears. 
   Would prefer if it assumed the same connection you opened it from.

#2. Opening a File or creating a new script
Open or create a script
Modify as needed
Press F5 to run - CONNECTION appears
   Would prefer if it assumed the current connection.

**Comment by anthonydresser** [comment]
I believe this is intended behavior and this is actually a regression.

**Comment by kburtram** [comment]
The current behavior is "by design" though I agree the design is currently incorrect.

Initially we only supported `Script as Create` scenario throught the `Go to Definition` command.  The problem with auto-connecting when generating a create statement is that the entire statement will be highlighted as a syntax error as a duplicate database object.  In the Go to Definition scenario having the CREATE highlighted with the red squiggly seemed undesirable.

In the `Script as Alter`, `Script as Execute`, etc. the editor certainly should be connected.  We're currently thinking we'll update the behavior to connect for any scripting operation other than `Script as Create`.  I guess we could further refine this to only not connect in `Go to Definition` scripting and have the explicit `Script as Create` command connect assuming the typical scenario is to alter the CREATE statement and execute it on the current connection.

**Comment by barryseymour** [comment]
If you generate a CREATE script, could you not preface with a DROP [objecttype] IF EXISTS [objectname]? That would prevent the syntax error notification.

**Comment by kburtram** [comment]
@barryseymour that's a good suggestion, thought I'm not sure we would want to add a drop statement into the `Script as Create` to avoid any user confusion or accidents.  SSMS has a separate `Script Drop and Create` which we could also consider.  I'll discuss a bit with our PM and try to figure out what makes the most sense here.  Thanks!
