### ISSUE TITLE
Databases folder is not visible for user having default database other than master

### ISSUE THREAD

**Issue by syogananda** [Microsoft/sqlopsstudio#836]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.15063
---

Steps to Reproduce:

1.Change the default database other than master for a user.
2.Login with that user you'll not get databases folder, you can only have access to the default database.

**Comment by MattIrv** [comment]
This should be fixed in the latest release, as long as you leave the database name blank when connecting. See https://github.com/Microsoft/sqlopsstudio/issues/590 for more details about the bug and its fix.

@syogananda It looks like you're using an old version of SQL Ops Studio. Could you try updating to the newest release (https://docs.microsoft.com/en-us/sql/sql-operations-studio/download) and let us know if that solves the issue for you? Thanks
