### ISSUE TITLE
ALT+F1 [Feature request]

### ISSUE THREAD

**Issue by Ryukote** [Microsoft/sqlopsstudio#874]
I have noticed that there is no feature like in SSMS and that is ALT+F1 when you select table name in sql editor to see more info about that table.

Is there already this feature but I need to call it with something else or it is missing?
If it is missing this would be nice feature to add.

**Comment by kburtram** [comment]
I haven't used that SSMS feature before but it seems pretty helpful.  We don't currently have this feature in SQL Ops Studio yet.

For reference it appears to output a list of table, view, etc. for the current DB in one resultset and schema info for the table in a second resultset.

**Comment by kevcunnane** [comment]
We do have this - see https://github.com/Microsoft/sqlopsstudio/issues/441 for instructions on how to use this. We changed the shortcut key from SSMS but otherwise you should have the full functionality from SSMS. Please let us know if you find any issues. I’ll close this for now since it’s available in the latest releases.

**Comment by Ryukote** [comment]
I am still new to sql ops so I couldn't find what it's shortkey was. I have modified it and now I can see what I want with alt+f1. Thank you for info.
