### ISSUE TITLE
too much whitespace in tree

### ISSUE THREAD

**Issue by Spongman** [Microsoft/sqlopsstudio#885]
- SQL Operations Studio Version:
````
Version 0.26.7
Commit 723c7cb3bfd80d87fc8a1141632089cd4808495c
Date 2018-02-16T21:34:47.034Z
Shell 1.7.11
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
````

IMHO:
````
  ServerTreeRenderer.CONNECTION_HEIGHT = 25;
  ServerTreeRenderer.OBJECTEXPLORER_HEIGHT = 25;
````

looks much better and requires less scrolling:

![image](https://user-images.githubusercontent.com/1088194/37226581-3fe54d6e-238f-11e8-922a-23622b798b0e.png)

**Comment by kburtram** [comment]
@Spongman I sent a PR with your proposed change.  I'll get some feedback from a couple folks to determine if there is agreement on the preferred spacing.

**Comment by Spongman** [comment]
i'm curious as to why you guys don't use CSS for this kind of styline. maybe it's a performance thing?

**Comment by kburtram** [comment]
@Spongman not sure why that particular setting isn't done in CSS.  I think the tree logic was forked from VS Codes file explorer and that's how it was originally done, IIRC.  We do generally try to use CSS for most styling, but things are done differently in some cases.

I'll close this issue since I've merged the change to reduce the spacing to 25px as suggested.  Thanks!
