### ISSUE TITLE
Default database only shows for connections with no database selected

### ISSUE THREAD

**Issue by bartedgerton** [Microsoft/sqlopsstudio#92]
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce:  Create connection to a server without specifying a database.   If the login does not have a default database defined, then all databases are shown in the SERVERS pane and can be drilled into.  If the login has a default database defined, then there is no way to navigate/drill down to other databases on the same server.

**Comment by llali** [comment]
@bartedgerton the workaround would be to set "master" as database name. Then the connection would have all the databases to browse to.

**Comment by kburtram** [comment]
If the connect is to a system database then all the databases will be displayed under the server.  I'll close this since there is a workaround.  We have discussed options like (1) get rid of database connections and always connect to server (2) having a checkbox to indicate if the connection should be to the server or a particular database.  We haven't seen much user confusion yet, so we haven't prioritized this redesign.
