### ISSUE TITLE
Connection Dialog Saved Connections & Recent Connections empty

### ISSUE THREAD

**Issue by kburtram** [Microsoft/sqlopsstudio#958]
- SQL Operations Studio Version: 0.27.0

Steps to Reproduce:
1. Connect to some servers and save them

Expected: Recent and Saved is populated with servers

Actual: Connection dialog saved and recent connections empty

![screen1](https://user-images.githubusercontent.com/599935/37798630-8e828dc4-2dda-11e8-9e5b-3fc270c66dc9.png)

**Comment by MattIrv** [comment]
Sure I'll take a look

**Comment by mrlife** [comment]
Will this be released as a patch fix or not until April release?

**Comment by MattIrv** [comment]
@mrlife This bug only should have ever appeared in dev builds and in our 0.27.0 preview, not in any released builds. What version of SQL Operations Studio are you using? If you're seeing this bug and running the 0.27.0 preview, please upgrade to a newer version. Otherwise please let me know and I'll look into it some more. Thanks!

**Comment by mrlife** [comment]
@MattIrv Thanks for clarifying. The insiders builds are pre-preview, but I had not realized that.

**Comment by kburtram** [comment]
@mrlife yes, the `insiders` builds are straight off master and are what we're using to stabilize the product in preparation for the monthly official `stable` build.  I'll make sure to make this more explicit in the build release notes.
