### ISSUE TITLE
Expect query plan when select XML showplan in the result grid

### ISSUE THREAD

**Issue by AbbiePetcht** [Microsoft/sqlopsstudio#967]
Select XML showplan in the result, should open query plan 

Scenario: It is the main scenario for execute sp_whoisactive to get plans
1. connect to server that have sp_whoisactive (sqltools2017-3)
2. EXEC sp_WhoIsActive
        @get_plans = 1

Actual result:
It opens up new xml editor file.

Expect result:
It should open query plan

Simple repro step: 
1. open editor and run "select * from sys.tables"
2. select "explain"
3. go to result grid and select the showplan link

**Comment by anthonydresser** [comment]
This might be difficult considering it's just another xml that is the format of a showplan, We would need to be able to parse it and test it for showplan, which i'm not sure its worth it, when a user than click showplan for a query. Before we had a feature that if you selected showplan as the language type rather than xml it would show the plan in the editor? @kburtram I remember this being demoed after the "hackathon" we had, not sure if it's still in the product.

**Comment by StevenHibble** [comment]
I run sp_whoisactive with @get_plans = 1 _a lot_ in SSMS. It helps me tune my end users' queries in real time. Now that the whoisactive extension is live (and explicitly has a "Get plans" button), I'd appreciate this support. 

It seems that SSMS's implementation involves:

1. Recognize it's an execution plan
2. Save the XML as a .sqlplan file somewhere
3. Open that file
